config/routes.rb
Rails.application.routes.draw do
  resources :kanbans
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :kanban_column
  # acts_as_list
end

app/models/kanban.rb
class Kanban < ApplicationRecord
  has_many :kanban_columns
  # acts_as_list
end

app/models/kanban_column.rb
class KanbanColumn < ApplicationRecord
  belongs_to :kanban
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
end

app/controllers/kanbans_controller.rb
class KanbansController < ApplicationController
  before_action :set_kanban, only: %i[ show edit update destroy ]

  # GET /kanbans or /kanbans.json
  def index
    @kanbans = Kanban.all
  end

  # GET /kanbans/1 or /kanbans/1.json
  def show
  end

  # GET /kanbans/new
  def new
    @kanban = Kanban.new
  end

  # GET /kanbans/1/edit
  def edit
  end

  # POST /kanbans or /kanbans.json
  def create
    @kanban = Kanban.new(kanban_params)

    respond_to do |format|
      if @kanban.save
        format.html { redirect_to kanban_url(@kanban), notice: "Kanban was successfully created." }
        format.json { render :show, status: :created, location: @kanban }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kanbans/1 or /kanbans/1.json
  def update
    respond_to do |format|
      if @kanban.update(kanban_params)
        format.html { redirect_to kanban_url(@kanban), notice: "Kanban was successfully updated." }
        format.json { render :show, status: :ok, location: @kanban }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kanbans/1 or /kanbans/1.json
  def destroy
    @kanban.destroy!

    respond_to do |format|
      format.html { redirect_to kanbans_url, notice: "Kanban was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kanban
      @kanban = Kanban.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kanban_params
      params.require(:kanban).permit(:name, :description, :cards)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kanbans/_form.html.erb
<%= simple_form_for(@kanban) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :cards %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/kanbans/_kanban.html.erb
<div id="<%= dom_id kanban %>">
  <p>
    <strong>Name:</strong>
    <%= kanban.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= kanban.description %>
  </p>

  <p>
    <strong>Cards:</strong>
    <%= kanban.cards %>
  </p>

</div>

app/views/kanbans/edit.html.erb
<h1>Editing kanban</h1>

<%= render "form", kanban: @kanban %>

<br>

<div>
  <%= link_to "Show this kanban", @kanban %> |
  <%= link_to "Back to kanbans", kanbans_path %>
</div>

app/views/kanbans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Kanbans</h1>

<div id="kanbans">
  <% @kanbans.each do |kanban| %>
    <%= render kanban %>
    <p>
      <%= link_to "Show this kanban", kanban %>
    </p>
  <% end %>
</div>

<%= link_to "New kanban", new_kanban_path %>

app/views/kanbans/new.html.erb
<h1>New kanban</h1>

<%= render "form", kanban: @kanban %>

<br>

<div>
  <%= link_to "Back to kanbans", kanbans_path %>
</div>

app/views/kanbans/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @kanban %>
<div class="kanban" data-id="<%= @kanban.id %>">
  <% @kanban.kanban_columns.each do |column| %>
    <ul class="kanban-col" data-col-id=<%= column.id %> data-controller="sortable" data-sortable-animation-value="150">
      <li class="kanban-col-name"><%= column.name %></li>
      <% column.cards.sort_by{ |card| card.position }.each do |item| %>
        <li class="kanban-col-item" data-item-id=<%= item.id %>>
          <%= item.content %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>
<div class="experiment">
  <%# experiment %>
  <table class="table table-bordered" id="classroom-table">
    <thead>
      <tr>
        <th class='kanban-col-name'>Column 1</th>
        <th class='kanban-col-name'>Aisle</th>
        <th class='kanban-col-name'>Column 2</th>
      </tr>
    </thead>
    <tbody>
      <td>
        <div class="list-group" id="column1" data-controller="sortable" data-sortable-animation-value="150">
          <li class="list-group-item kanban-col-item column-student">
            Tatsuya Hirotani
          </li>
          <li class="list-group-item kanban-col-item column-student">
            Kelly Fisher
          </li>
        </div>
      </td>
      <td>
        <div class="list-group" id="aisle1">
        </div>
      </td>
      <td>
        <div class="list-group" id="column2" data-controller="sortable" data-sortable-animation-value="150">
          <li class="list-group-item kanban-col-item column-student">
            Ariel Cardinal
          </li>
          <li class="list-group-item kanban-col-item column-student">
            Sakura Taiga
          </li>
          <li class="list-group-item kanban-col-item column-student">
            Shinoka Tamanaka
          </li>
        </div>
      </td>
    </tbody>
  </table>
  <%# experiment end %>
</div>
<div>
  <%= link_to "Edit this kanban", edit_kanban_path(@kanban) %> |
  <%= link_to "Back to kanbans", kanbans_path %>
  <%= button_to "Destroy this kanban", @kanban, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KanbanApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>